# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\asus\Desktop\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 300, 261, 31))
        self.lineEdit_4.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 370, 261, 31))
        self.lineEdit_3.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.signup_2 = QtWidgets.QPushButton(Dialog)
        self.signup_2.setGeometry(QtCore.QRect(320, 560, 121, 28))
        self.signup_2.setStyleSheet("background-color: rgb(137, 137, 159);\n"
"color: rgb(255, 255, 255);\n"
"font-size:14pt")
        self.signup_2.setObjectName("signup_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 300, 81, 31))
        self.label_5.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-size:15pt;")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 370, 121, 31))
        self.label_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-size:15pt;")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(160, 80, 171, 71))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size:28pt;")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 220, 261, 31))
        self.lineEdit_5.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 220, 81, 31))
        self.label_7.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-size:15pt;")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 470, 261, 31))
        self.lineEdit_6.setStyleSheet("font-size:14pt;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(40, 450, 111, 31))
        self.label_8.setMinimumSize(QtCore.QSize(111, 31))
        self.label_8.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-size:15pt;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 480, 111, 31))
        self.label_9.setMinimumSize(QtCore.QSize(111, 31))
        self.label_9.setStyleSheet("color: rgb(170, 0, 0);\n"
"font-size:15pt;")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.signup_2.setText(_translate("Dialog", "Sign Up"))
        self.label_5.setText(_translate("Dialog", "Email"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_6.setText(_translate("Dialog", "Sign Up"))
        self.label_7.setText(_translate("Dialog", "Name"))
        self.label_8.setText(_translate("Dialog", "Conform "))
        self.label_9.setText(_translate("Dialog", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_1()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
