# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'patient_reportKNalVb.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QMainWindow, QSizePolicy, QWidget)

class Ui_pdfWindow(object):
    def setupUi(self, pdfWindow):
        if not pdfWindow.objectName():
            pdfWindow.setObjectName(u"pdfWindow")
        pdfWindow.resize(800, 600)
        self.centralwidget = QWidget(pdfWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color:rgba(255,255,255,210);\n"
"")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.backFrame = QFrame(self.centralwidget)
        self.backFrame.setObjectName(u"backFrame")
        self.backFrame.setFrameShape(QFrame.StyledPanel)
        self.backFrame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.backFrame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.frontFrame = QFrame(self.backFrame)
        self.frontFrame.setObjectName(u"frontFrame")
        font = QFont()
        font.setBold(True)
        self.frontFrame.setFont(font)
        self.frontFrame.setFrameShape(QFrame.StyledPanel)
        self.frontFrame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frontFrame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(540, 100, 171, 151))
        self.label.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_2 = QLabel(self.frontFrame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 130, 161, 16))
        font1 = QFont()
        font1.setFamilies([u"Times New Roman"])
        font1.setPointSize(14)
        font1.setBold(False)
        self.label_2.setFont(font1)
        self.label_2.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_3 = QLabel(self.frontFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 160, 61, 21))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(self.frontFrame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 200, 161, 16))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_5 = QLabel(self.frontFrame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(80, 240, 161, 21))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_6 = QLabel(self.frontFrame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(270, 20, 231, 16))
        font2 = QFont()
        font2.setFamilies([u"Times New Roman"])
        font2.setPointSize(14)
        font2.setBold(True)
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.frontFrame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 280, 211, 16))
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_8 = QLabel(self.frontFrame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(80, 320, 101, 16))
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_9 = QLabel(self.frontFrame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(440, 420, 141, 21))
        font3 = QFont()
        font3.setFamilies([u"Times New Roman"])
        font3.setPointSize(12)
        font3.setBold(False)
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_10 = QLabel(self.frontFrame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(250, 130, 251, 20))
        font4 = QFont()
        font4.setFamilies([u"Times New Roman"])
        font4.setPointSize(12)
        self.label_10.setFont(font4)
        self.label_10.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_11 = QLabel(self.frontFrame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(130, 160, 241, 20))
        self.label_11.setFont(font4)
        self.label_11.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_12 = QLabel(self.frontFrame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(250, 200, 161, 20))
        self.label_12.setFont(font4)
        self.label_12.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_13 = QLabel(self.frontFrame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(250, 240, 161, 20))
        self.label_13.setFont(font4)
        self.label_13.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_14 = QLabel(self.frontFrame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 280, 161, 20))
        self.label_14.setFont(font4)
        self.label_14.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_15 = QLabel(self.frontFrame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(590, 420, 151, 20))
        font5 = QFont()
        font5.setFamilies([u"Times New Roman"])
        font5.setPointSize(9)
        self.label_15.setFont(font5)
        self.label_15.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.frontFrame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(70, 510, 581, 21))
        self.label_16.setFont(font3)
        self.label_16.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.frontFrame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(440, 440, 51, 21))
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_18 = QLabel(self.frontFrame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(470, 440, 261, 20))
        self.label_18.setFont(font4)
        self.label_18.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.label_18.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_2.addWidget(self.frontFrame)


        self.horizontalLayout.addWidget(self.backFrame)

        pdfWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(pdfWindow)

        QMetaObject.connectSlotsByName(pdfWindow)
    # setupUi

    def retranslateUi(self, pdfWindow):
        pdfWindow.setWindowTitle(QCoreApplication.translate("pdfWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("pdfWindow", u"IMAGE INPUT HERE", None))
        self.label_2.setText(QCoreApplication.translate("pdfWindow", u"Name of the Patient:", None))
        self.label_3.setText(QCoreApplication.translate("pdfWindow", u"Age:", None))
        self.label_4.setText(QCoreApplication.translate("pdfWindow", u"Left Eye Deviation:", None))
        self.label_5.setText(QCoreApplication.translate("pdfWindow", u"Right Eye Deviation:", None))
        self.label_6.setText(QCoreApplication.translate("pdfWindow", u"PATIENT REPORT", None))
        self.label_7.setText(QCoreApplication.translate("pdfWindow", u"Total Eye Deviation:", None))
        self.label_8.setText(QCoreApplication.translate("pdfWindow", u"Remarks:", None))
        self.label_9.setText(QCoreApplication.translate("pdfWindow", u"Report Generated by:", None))
        self.label_10.setText(QCoreApplication.translate("pdfWindow", u"NAME", None))
        self.label_11.setText(QCoreApplication.translate("pdfWindow", u"AGE", None))
        self.label_12.setText(QCoreApplication.translate("pdfWindow", u"LEFT DEVIA.", None))
        self.label_13.setText(QCoreApplication.translate("pdfWindow", u"RIGHT DEVIA.", None))
        self.label_14.setText(QCoreApplication.translate("pdfWindow", u"TOTAL DEVIA.", None))
        self.label_15.setText(QCoreApplication.translate("pdfWindow", u"FIRST NAME LAST NAME OF USER", None))
        self.label_16.setText(QCoreApplication.translate("pdfWindow", u"This is a digitally generated report made using STRABIS-T application", None))
        self.label_17.setText(QCoreApplication.translate("pdfWindow", u"On:", None))
        self.label_18.setText(QCoreApplication.translate("pdfWindow", u"DATE", None))
    # retranslateUi

